# -*- coding: utf-8 -*-

# ID of public database
NCBI_ID = 1
PHAGES_DB_ID = 2

# ID of taxonomie
STRAIN_ID = 1
SPECIES_ID = 2
GENUS_ID = 3
FAMILY_ID = 4

# ID of each variable for the validity (found in inphinity DB)
LABORATORY_TESTED = 1
VALIDE_IN_THE_MIDDLE = 2
NO_VALID = 3
NOT_VALIDATE = 4

# Lysis Type
CLEAR_LYSIS = 5
SEMI_CLEAR_LYSIS = 6
OPAQUE_LYSIS = 7

# Dilution > 1e7
CLEAR_LYSIS_1E7PLUS = 8
SEMI_CLEAR_LYSIS_1E7PLUS = 10

# Dilution < 1e7
CLEAR_LYSIS_1E7MINUS = 9
SEMI_CLEAR_LYSIS_1E7MINUS = 11

ALL_CLEAR_LYSIS = [CLEAR_LYSIS, CLEAR_LYSIS_1E7PLUS, CLEAR_LYSIS_1E7MINUS]
ALL_SEMI_CLEAR_LYSIS = [SEMI_CLEAR_LYSIS, SEMI_CLEAR_LYSIS_1E7PLUS, SEMI_CLEAR_LYSIS_1E7MINUS]

# ID of each variable for the interaction type (found in inphinity DB)
NEGATIVE_INTERACTION = 0
POSITIVE_INTERACTION = 1